#!/usr/bin/env python3
"""Embed a deterministic Composer autoloader recovery bundle in doctor.php."""

from __future__ import annotations

import base64
import gzip
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCTOR = ROOT / "doctor.php"
BACKUP = ROOT / "bootstrap" / "autoload_backup"
START = "// BEGIN EMBEDDED AUTOLOADER BUNDLE (generated by tools/build-doctor-bundle.py)"
END = "// END EMBEDDED AUTOLOADER BUNDLE"


def main() -> None:
    files = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(BACKUP.glob("*.php"))
    }
    if "autoload.php" not in files or "autoload_psr4.php" not in files:
        raise SystemExit("autoload backup is incomplete")

    raw = json.dumps(files, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode()
    compressed = gzip.compress(raw, compresslevel=9, mtime=0)
    encoded = base64.b64encode(compressed).decode("ascii")
    wrapped = [encoded[i : i + 120] for i in range(0, len(encoded), 120)]
    payload = "\n".join(wrapped)
    digest = hashlib.sha256(compressed).hexdigest()

    generated = (
        f"{START}\n"
        f"const DOCTOR_BUNDLE_SHA256 = '{digest}';\n"
        "const DOCTOR_BUNDLE_BASE64 = <<<'HUVANTI_AUTOLOAD_BUNDLE'\n"
        f"{payload}\n"
        "HUVANTI_AUTOLOAD_BUNDLE;\n"
        f"{END}"
    )

    source = DOCTOR.read_text(encoding="utf-8")
    start = source.index(START)
    end = source.index(END, start) + len(END)
    DOCTOR.write_text(source[:start] + generated + source[end:], encoding="utf-8")

    print(
        f"Embedded {len(files)} files: {len(raw):,} raw bytes, "
        f"{len(compressed):,} compressed bytes, sha256 {digest}"
    )


if __name__ == "__main__":
    main()
